const fs = require("node:fs");
const path = require("node:path");

/* Merge @fontsource/inter @font-face rules: keep only the vietnamese + latin
   subsets (no latin-ext), drop the .woff fallback (woff2 only), rewrite urls
   to absolute paths so the paged.js polisher doesn't rebase them when
   inlining CSS. */
function buildInterCss() {
  const pkg = path.join("node_modules", "@fontsource", "inter");
  return ["400.css", "700.css"]
    .flatMap((f) => fs.readFileSync(path.join(pkg, f), "utf8").match(/@font-face\s*{[^}]*}/g) || [])
    .filter((block) => /inter-(vietnamese|latin)-\d+-normal\.woff2/.test(block))
    .map((block) =>
      block
        .replace(/,?\s*url\([^)]*\.woff\)\s*format\('woff'\)/g, "")
        .replace(/url\(\.\/files\//g, "url(/fonts/files/")
    )
    .join("\n");
}

/* Autolink: escape HTML then wrap URLs (http/https) in <a> - use with
   | autolink | safe in the template. Keeps content links clickable in both
   the HTML view and the PDF. */
function escapeHtml(s) {
  return String(s)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

module.exports = function (eleventyConfig) {
  eleventyConfig.addPassthroughCopy({ "src/css": "css" });

  eleventyConfig.addFilter("autolink", (value) => {
    if (!value) return value;
    return escapeHtml(value).replace(
      /(https?:\/\/[^\s"'<>]+)/g,
      (url) => '<a href="' + url + '" target="_blank" rel="noopener">' + url + "</a>"
    );
  });

  /* PDF generated by scripts/build-pdf.mjs - passthrough so it survives rebuilds */
  eleventyConfig.addPassthroughCopy({ "src/cv.pdf": "cv.pdf" });

  eleventyConfig.on("eleventy.after", () => {
    /* Self-host paged.js (npm dependency) → _site/vendor */
    fs.mkdirSync(path.join("_site", "vendor"), { recursive: true });
    fs.copyFileSync(
      path.join("node_modules", "pagedjs", "dist", "paged.polyfill.js"),
      path.join("_site", "vendor", "paged.polyfill.js")
    );

    /* Self-host Inter (npm @fontsource) → _site/fonts, vietnamese + latin subsets only, weights 400/700 */
    const srcFiles = path.join("node_modules", "@fontsource", "inter", "files");
    const destFiles = path.join("_site", "fonts", "files");
    fs.mkdirSync(destFiles, { recursive: true });
    fs.readdirSync(srcFiles)
      .filter((f) => /^inter-(vietnamese|latin)-(400|700)-normal\.woff2$/.test(f))
      .forEach((f) => fs.copyFileSync(path.join(srcFiles, f), path.join(destFiles, f)));
    fs.writeFileSync(path.join("_site", "fonts", "inter.css"), buildInterCss());
  });

  return {
    dir: {
      input: "src",
      output: "_site",
      includes: "_includes",
      data: "_data"
    }
  };
};
